all:
  hosts:
    controlplane-node:
      ansible_host: 35.95.85.216
      ansible_user: ubuntu
    worker-node:
      ansible_host: 44.244.128.229
      ansible_user: ubuntu

  children:
    controlplane:
      hosts:
        controlplane-node:
    worker:
      hosts:
        worker-node:

  vars:
    ansible_ssh_private_key_file: ~/.ssh/ec2_key.pem
    ansible_python_interpreter: /usr/bin/python3